### ISSUE TITLE
Permission denied for exec in rootless docker

### ISSUE THREAD

**Issue by Caltanjun** [eth-educators/eth-docker#317] opened 2021-11-07 09:50 UTC
Context:
 - ubuntu 20.04
 - docker rootless
 - running `docker-compose run --user="geth" execution` (or any service with a script as entrypoint)  

  
I got the following result:
```sh
Creating eth-docker_execution_run ... done
standard_init_linux.go:228: exec user process caused: permission denied
ERROR: 1
```

Different error without the `--user` parameter:
```
su-exec: /usr/local/bin/docker-entrypoint.sh: Permission denied
```

It works when permissions are set this way in the dockerfile:
```dockerfile
...
COPY ./docker-entrypoint.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh  # added line
```

Is there a better way of fixing this ?

**Comment by yorickdowne** [comment] 2021-11-10 06:16
Interesting. I haven't tried rootless docker. I'll need to play with this a little.

**Comment by yorickdowne** [comment] 2021-11-20 15:21
Okay I installed rootless docker-ce and I cannot reproduce this, with the default user or with a `geth` user. Tried with besu and geth.

**Comment by Caltanjun** [comment] 2021-11-20 18:14
Ok weird. When running `docker info | grep rootless` do you see `rootless` as a result ?

**Comment by yorickdowne** [comment] 2022-01-29 12:51
In a nutshell yes, I guarantee this was a rootless install. 

A lot of the entrypoint scripts are gone and the remaining ones are all 775 already in the filesystem and get copied into the images that way. Does this issue persist for you?

**Comment by yorickdowne** [comment] 2022-03-04 12:51
Closing as there is no further activity.

**Closed by yorickdowne** 2022-03-04 12:51 UTC
