### ISSUE TITLE
nethermind-prune error 7

### ISSUE THREAD

**Issue by davidkassa** [eth-educators/eth-docker#1042] opened 2022-11-03 13:32 UTC
when running ./ethd nethermind-prune, I get the following error:

```
WARNING - this will restart Nethermind and prune its database in the background. Do you wish to continue? (No/Yes) Yes

Starting Nethermind prune

Creating eth-docker_set-prune-marker_run ... done
Stopping eth-docker_execution_1 ... done
Going to remove eth-docker_execution_1
Removing eth-docker_execution_1 ... done
eth-docker_mev-boost_1 is up-to-date
eth-docker_node-exporter_1 is up-to-date
eth-docker_ethereum-metrics-exporter_1 is up-to-date
eth-docker_cryptowat-exporter_1 is up-to-date
Creating eth-docker_execution_1 ... 
eth-docker_cf-ddns_1 is up-to-date
eth-docker_cadvisor_1 is up-to-date
eth-docker_loki_1 is up-to-date
eth-docker_consensus_1 is up-to-date
eth-docker_json-exporter_1 is up-to-date
eth-docker_blackbox-exporter_1 is up-to-date
eth-docker_traefik_1 is up-to-date
eth-docker_promtail_1 is up-to-date
eth-docker_validator_1 is up-to-date
eth-docker_prometheus_1 is up-to-date
Creating eth-docker_execution_1 ... done
Waiting 10 seconds for Nethermind to be up
Creating eth-docker_set-prune-marker_run ... done
ERROR: 7
Unable to start prune. This is likely a bug.
```

Should be pretty vanilla install:
```
This is eth-docker v2.2.0

Lighthouse v3.2.1-6d5a2b5
BLS library: blst-modern
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (true)

2022-11-03 13-31-17.0487|Nethermind starting initialization.
2022-11-03 13-31-17.1318|Loading embedded plugins
2022-11-03 13-31-17.1321|  Found plugin type Nethermind.Consensus.AuRa.AuRaPlugin
2022-11-03 13-31-17.1321|  Found plugin type Nethermind.Consensus.Clique.CliquePlugin
2022-11-03 13-31-17.1322|  Found plugin type Nethermind.Consensus.Ethash.EthashPlugin
2022-11-03 13-31-17.1322|  Found plugin type Nethermind.Consensus.Ethash.NethDevPlugin
2022-11-03 13-31-17.1322|  Found plugin type Nethermind.Hive.HivePlugin
2022-11-03 13-31-17.1322|  Found plugin type Nethermind.UPnP.Plugin.UPnPPlugin
2022-11-03 13-31-17.1420|Loading 9 assemblies from /nethermind/plugins
2022-11-03 13-31-17.1422|Loading assembly Nethermind.Mev
2022-11-03 13-31-17.1471|  Found plugin type Nethermind.Mev
2022-11-03 13-31-17.1471|Loading assembly Nethermind.Api
2022-11-03 13-31-17.1492|Loading assembly Nethermind.Consensus.AuRa
2022-11-03 13-31-17.1531|Loading assembly Nethermind.HealthChecks
2022-11-03 13-31-17.1545|  Found plugin type Nethermind.HealthChecks
2022-11-03 13-31-17.1545|Loading assembly Nethermind.Init
2022-11-03 13-31-17.1555|Loading assembly Nethermind.EthStats
2022-11-03 13-31-17.1564|  Found plugin type Nethermind.EthStats
2022-11-03 13-31-17.1564|Loading assembly Nethermind.Merge.Plugin
2022-11-03 13-31-17.1597|  Found plugin type Nethermind.Merge.Plugin
2022-11-03 13-31-17.1597|Loading assembly Nethermind.Merge.AuRa
2022-11-03 13-31-17.1603|  Found plugin type Nethermind.Merge.AuRa
2022-11-03 13-31-17.1603|Loading assembly Nethermind.AccountAbstraction
2022-11-03 13-31-17.1638|  Found plugin type Nethermind.AccountAbstraction

Version: 1.14.5+380bf9c9
Commit: 380bf9c966844baf43fc47928cd5165b5d696ebc
Build Date: 0001-01-01 00:00:00Z
OS: Linux x64
Runtime: .NET 6.0.10


mev-boost v1.3.2

prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64

Grafana Version 9.2.3 (commit: ec9c2ed029, branch: HEAD)
```

**Comment by yorickdowne** [comment] 2022-11-04 07:57
I had another user with this as well. It might be that Nethermind wasn't fully up, yet. You can try `docker-compose run --rm set-prune-marker "curl -s --data {\\\"method\\\":\\\"admin_prune\\\",\\\"params\\\":[],\\\"id\\\":1,\\\"jsonrpc\\\":\\\"2.0\\\"} -H Content-Type:\ application/json http://execution:8545"` manually, then check logs. I've also increased the debug output for when this happens.

**Comment by yorickdowne** [comment] 2022-11-04 14:51
Closing this for now. Engage on ethstaker Discord pls if this persists.

**Comment by davidkassa** [comment] 2022-11-04 16:40
Thanks! Still timed out, but running the command you listed in the output seemed to work fine.

**Comment by yorickdowne** [comment] 2022-11-04 18:41
Very odd. I am syncing a Nethermind so I can add a "wait for up to 30 sec for Nethermind to respond" loop.

If it's not that, then it's something with the old docker-compose.

**Comment by yorickdowne** [comment] 2022-11-05 02:29
I am unable to reproduce this so far. Can you give me a little more, please:
- Is your user part of the `docker` group?
- When you tried this again with a new version of eth-docker, what was the debug output?

**Comment by yorickdowne** [comment] 2022-11-07 16:34
It's unrelated to whether user is part of `docker`. I cannot reproduce. Additional debug has been added. Closing once more; if you can reproduce, debug data will be helpful.

**Closed by yorickdowne** 2022-11-07 16:34 UTC

**Comment by davidkassa** [comment] 2022-11-07 16:48
Ran without error now.

**Comment by thomkeh** [comment] 2022-11-19 12:15
I also had a problem with pruning that was a bit difficult to debug. I'm posting it here in case it's useful for anybody else.

My problem was that I had set a custom value for `--Pruning.FullPruningMaxDegreeOfParallelism` in `nethermind.yml`. This caused a problem because `nethermind/docker-entrypoint.sh` overwrites that value and Nethermind does not like it when a flag is specified twice. So what happened was Nethermind failed to start, but then silently tried to start again. This time the pruning-marker was already removed, so it just started normally without any pruning settings. `ethd` didn't notice that and still tried to do the `curl` command, but that failed because `Admin` was not part of `EnabledModules`.

In the end it was easy to fix (just remove the `--Pruning.FullPruningMaxDegreeOfParallelism` setting from `nethermind.yml`) but finding out that that was the problem was quite tricky.

**Comment by yorickdowne** [comment] 2022-11-19 21:54
Interesting. What were you looking to set it to? Entrypoint defaults to half the cores or half the threads if there are threads. That might be a little aggressive.

**Comment by thomkeh** [comment] 2022-11-19 22:03
On Sat, 2022-11-19 at 13:55 -0800, yorickdowne wrote:
> Interesting. What were you looking to set it to? Entrypoint defaults
> to half the cores or half the threads if there are threads. That
> might be a little aggressive.
> 

I think half the cores is a good number. I just didn't want
Nethermind's default behavior, which is, I think, number of cores, so I
just set it to 4 (half of cores would have been 6).

Again, I'm completely fine with the current behavior; I just didn't
know it worked like it does.
