### ISSUE TITLE
./ethd terminate removed node in other directories

### ISSUE THREAD

**Issue by d1onys1us** [eth-educators/eth-docker#1453] opened 2023-07-24 06:53 UTC
hello, the setup that i work with is that i have several folders where i clone eth-docker. so for example i had:
- eth-docker-geth-1
- eth-docker-geth-2

eth-docker-geth-1 was a fully synced archive node. i was spinning up eth-docker-geth-2 for demo purposes. when i was done with it, i wanted to remove the node. instead of doing `rm -rf eth-docker-geth-2` (should i have done this?), i ran an `./ethd terminate` in that folder.

the docs implied to me that this would just remove the archive node for eth-docker-geth-2, but it looks like it removed both! is this expected behavior? when i spin up `eth-docker-geth-1` it looks like the chain head is back to 0 :(.

## questions
1. did i misuse ./ethd terminate or did i really lose my other archive node?
2. can we enhance the docs to make sure it's clear this could remove other synced nodes on the host machine?

**Comment by yorickdowne** [comment] 2023-07-25 04:21
This is unexpected and a bug. A nasty one. I'll dig.

**Comment by yorickdowne** [comment] 2023-07-25 04:27
I cannot reproduce this. Do you still have the logs from when this happened?
```
ubuntu@eth-testing:~/eth-docker-geth-2$ ./ethd terminate
WARNING - this action will destroy all data stores for this Ethereum node. Do you wish to continue? (No/Yes) yes
[+] Running 4/4
 ✔ Container eth-docker-geth-2-validator-1  Removed                                                                                                     0.3s 
 ✔ Container eth-docker-geth-2-execution-1  Removed                                                                                                     0.6s 
 ✔ Container eth-docker-geth-2-consensus-1  Removed                                                                                                     0.5s 
 ✔ Network eth-docker-geth-2_default        Removed                                                                                                     0.3s 
eth-docker-geth-2_jwtsecret
eth-docker-geth-2_prysmbeacon-data
eth-docker-geth-2_prysmvalidator-data
eth-docker-geth-2_reth-el-data

All containers stopped and all volumes deleted
```

```
ubuntu@eth-testing:~/eth-docker-geth-2$ docker ps
CONTAINER ID   IMAGE                                              COMMAND                  CREATED         STATUS                   PORTS                                                                                                NAMES
b9c13ff0fffb   prysm-validator:local                              "docker-entrypoint-v…"   2 minutes ago   Up 2 minutes                                                                                                                  eth-docker-geth-1-validator-1
8a49a9ad92b2   prysm-consensus:local                              "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes             0.0.0.0:9020->9020/tcp, 0.0.0.0:9020->9020/udp                                                       eth-docker-geth-1-consensus-1
120f0a8ba5ff   reth:local                                         "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes             8545-8546/tcp, 9001/tcp, 30303/tcp, 30303/udp, 0.0.0.0:30323->30323/tcp, 0.0.0.0:30323->30323/udp    eth-docker-geth-1-execution-1
```

**Comment by d1onys1us** [comment] 2023-07-27 19:47
> I cannot reproduce this. Do you still have the logs from when this happened?
> 
> ```
> ubuntu@eth-testing:~/eth-docker-geth-2$ ./ethd terminate
> WARNING - this action will destroy all data stores for this Ethereum node. Do you wish to continue? (No/Yes) yes
> [+] Running 4/4
>  ✔ Container eth-docker-geth-2-validator-1  Removed                                                                                                     0.3s 
>  ✔ Container eth-docker-geth-2-execution-1  Removed                                                                                                     0.6s 
>  ✔ Container eth-docker-geth-2-consensus-1  Removed                                                                                                     0.5s 
>  ✔ Network eth-docker-geth-2_default        Removed                                                                                                     0.3s 
> eth-docker-geth-2_jwtsecret
> eth-docker-geth-2_prysmbeacon-data
> eth-docker-geth-2_prysmvalidator-data
> eth-docker-geth-2_reth-el-data
> 
> All containers stopped and all volumes deleted
> ```
> 
> ```
> ubuntu@eth-testing:~/eth-docker-geth-2$ docker ps
> CONTAINER ID   IMAGE                                              COMMAND                  CREATED         STATUS                   PORTS                                                                                                NAMES
> b9c13ff0fffb   prysm-validator:local                              "docker-entrypoint-v…"   2 minutes ago   Up 2 minutes                                                                                                                  eth-docker-geth-1-validator-1
> 8a49a9ad92b2   prysm-consensus:local                              "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes             0.0.0.0:9020->9020/tcp, 0.0.0.0:9020->9020/udp                                                       eth-docker-geth-1-consensus-1
> 120f0a8ba5ff   reth:local                                         "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes             8545-8546/tcp, 9001/tcp, 30303/tcp, 30303/udp, 0.0.0.0:30323->30323/tcp, 0.0.0.0:30323->30323/udp    eth-docker-geth-1-execution-1
> ```

I will try to reproduce this in about a week from now, I do need my archive node up at the moment so don't want to risk going into downtime. Thanks for getting back on this, hopefully it's just a user error on my side!

**Comment by yorickdowne** [comment] 2023-07-28 04:23
Those logs say that the second install wasn’t touched and kept running, which is the expected behavior.

**Comment by yorickdowne** [comment] 2023-07-31 10:36
I'll close this for now. If you find evidence that this was an ethd bug, let's reopen it then.

**Closed by yorickdowne** 2023-07-31 10:36 UTC

**Comment by yorickdowne** [comment] 2023-08-15 04:17
I reproduced this. Thank you for the report - that is a nasty bug! Fixed now.
